// Regenerates everything under src/generated from openapi/v1.json.
//
//   node scripts/codegen.mjs              writes src/generated
//   node scripts/codegen.mjs --out <dir>  writes elsewhere (the drift test does this)
//
// The generator is run from this repository's own pinned install — never through
// `npx`, which would fetch whatever is current the moment the install is missing.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { contractHash, VENDORED_CONTRACT } from "./contract-hash.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const generator = join(root, "node_modules/openapi-typescript/bin/cli.js");

const flag = process.argv.indexOf("--out");
const outDir = flag === -1 ? join(root, "src/generated") : resolve(process.argv[flag + 1] ?? "");

if (!existsSync(generator)) {
  console.error("codegen: openapi-typescript is not installed. Run `pnpm install` first.");
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

execFileSync(process.execPath, [generator, VENDORED_CONTRACT, "-o", join(outDir, "openapi.ts")], {
  cwd: root,
  stdio: ["ignore", "ignore", "inherit"],
});

// The contract writes a nullable reference as `allOf: [{ $ref }, { type: [object,
// null] }]`, which openapi-typescript renders, faithfully, as
// `Ref & (Record<string, never> | null)`. That type is never null, so
// `earn.reward.id` compiled without a check and threw on an order too small to
// earn. Say what the contract means instead. A contract that switches to
// `anyOf: [{ $ref }, { type: "null" }]` already generates `Ref | null`, and this
// then matches nothing.
const NULLABLE_REF = /(components\["schemas"\]\["\w+"\]) & \(Record<string, never> \| null\)/g;
const generated = join(outDir, "openapi.ts");
writeFileSync(generated, readFileSync(generated, "utf8").replace(NULLABLE_REF, "$1 | null"));

const hash = contractHash(JSON.parse(readFileSync(VENDORED_CONTRACT, "utf8")));

writeFileSync(
  join(outDir, "contract.ts"),
  `/**
 * This file was auto-generated by scripts/codegen.mjs.
 * Do not make direct changes to the file.
 */

/**
 * Which contract this version of the SDK was generated from: the SHA-256 of
 * the API's OpenAPI document with keys sorted and code samples removed, so the
 * same contract hashes the same however it was formatted or served.
 */
export const CONTRACT_SHA256 = "${hash}";
`,
);

console.log(`codegen: wrote ${outDir} (contract ${hash.slice(0, 12)})`);
